include:
  - project: viz/ci/gitlabpipelines
    file: index.yml

# Templates

.kube:
  tags:
    - kubernetes
  variables:
    KUBERNETES_MEMORY_LIMIT: 2Gi
    KUBERNETES_MEMORY_REQUEST: 2Gi

.build-bcsb:
  extends: [".build-image-using-kaniko", ".kube"]

.publish-bcsb:
  extends: [".publish-image-using-kaniko", ".kube"]
  variables:
    CI_REGISTRY_IMAGE: bbpgitlab.epfl.ch:5050/viz/brayns/braynscircuitstudiobackend

# Django application

build:
  extends: .build-bcsb

publish-latest:
  extends: .publish-bcsb
  variables:
    REGISTRY_IMAGE_TAG: latest
  rules:
    - if: $CI_COMMIT_BRANCH == "develop"

publish-version:
  extends: .publish-bcsb
  variables:
    REGISTRY_IMAGE_TAG: $CI_COMMIT_TAG
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
    - if: $CI_COMMIT_TAG =~ /^[0-9]+\.[0-9]+(\.[0-9]+)?$/

# Django static files

build-static:
  extends: .build-bcsb
  variables:
    BUILD_PATH: ${CI_PROJECT_DIR}/static-nginx/

publish-static-latest:
  extends: .publish-bcsb
  variables:
    CI_REGISTRY_IMAGE: bbpgitlab.epfl.ch:5050/viz/brayns/braynscircuitstudiobackend/static
    BUILD_PATH: ${CI_PROJECT_DIR}/static-nginx/
    REGISTRY_IMAGE_TAG: latest
  rules:
    - if: $CI_COMMIT_BRANCH == "develop"

publish-static-version:
  extends: .publish-bcsb
  variables:
    CI_REGISTRY_IMAGE: bbpgitlab.epfl.ch:5050/viz/brayns/braynscircuitstudiobackend/static
    BUILD_PATH: ${CI_PROJECT_DIR}/static-nginx/
    REGISTRY_IMAGE_TAG: $CI_COMMIT_TAG
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
    - if: $CI_COMMIT_TAG =~ /^[0-9]+\.[0-9]+(\.[0-9]+)?$/
