include:
  - project: viz/ci/gitlabpipelines
    file: index.yml
    # Reference to https://bbpgitlab.epfl.ch/viz/ci/gitlabpipelines/-/tree/braynscircuitstudiobackend
    ref: braynscircuitstudiobackend
stages:
  - test
  - publish

# ------ Templates ------

.kube:
  tags:
    - kubernetes
  variables:
    KUBERNETES_MEMORY_LIMIT: 2Gi
    KUBERNETES_MEMORY_REQUEST: 2Gi


.common:
  variables:
    DOCKERFILE_PATH: $BUILD_PATH/Dockerfile
    CI_REGISTRY_IMAGE: bbpgitlab.epfl.ch:5050/viz/brayns/braynscircuitstudiobackend

.publish:
  extends:
    - .publish-image-using-kaniko
    - .kube
    - .common

# This is used for testing only during Merge Request
build:
  extends:
    - .build-image-using-kaniko
    - .kube
    - .common
  stage: test
  rules:
    - if: $CI_MERGE_REQUEST_IID

publish-latest:
  extends: .publish
  stage: publish
  variables:
    REGISTRY_IMAGE_TAG: latest
  rules:
    - if: $CI_COMMIT_BRANCH == "develop"

publish-version:
  extends: .publish
  variables:
    REGISTRY_IMAGE_TAG: $CI_COMMIT_TAG
  rules:
    - if: $CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+(\.[0-9]+)?$/

publish-stable:
  extends: .publish
  variables:
    REGISTRY_IMAGE_TAG: stable
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
