include:
  - project: viz/ci/gitlabpipelines
    file: index.yml
    # Reference to https://bbpgitlab.epfl.ch/viz/ci/gitlabpipelines/-/tree/braynscircuitstudiobackend
    ref: braynscircuitstudiobackend
stages:
  - test
  - test-static
  - publish
  - publish-static

# ------ Templates ------

.kube:
  tags:
    - kubernetes
  variables:
    KUBERNETES_MEMORY_LIMIT: 2Gi
    KUBERNETES_MEMORY_REQUEST: 2Gi

# ------ BCSB ------

.bcsb-common:
  variables:
    DOCKERFILE_PATH: $BUILD_PATH/bcsb.dockerfile
    CI_REGISTRY_IMAGE: bbpgitlab.epfl.ch:5050/viz/brayns/braynscircuitstudiobackend/bcsb

.bcsb-publish:
  extends:
    - .publish-image-using-kaniko
    - .kube
    - .bcsb-common

# This is used for testing only during Merge Request
bcsb-build:
  extends:
    - .build-image-using-kaniko
    - .kube
    - .bcsb-common
  stage: test
  rules:
    - if: $CI_MERGE_REQUEST_IID

# All new commits in the "develop" branch are built into a "latest" tag
bcsb-publish-latest:
  extends: .bcsb-publish
  variables:
    REGISTRY_IMAGE_TAG: latest
  rules:
    - if: $CI_COMMIT_BRANCH == "develop"

# Once a commit tag with version is pushed to "master", it builds a new version image
bcsb-publish-version:
  extends: .bcsb-publish
  variables:
    REGISTRY_IMAGE_TAG: $CI_COMMIT_TAG
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
    - if: $CI_COMMIT_TAG =~ /^[0-9]+\.[0-9]+(\.[0-9]+)?$/

# ------ BCSS ------

.bcss-common:
  variables:
    DOCKERFILE_PATH: $BUILD_PATH/bcss.dockerfile
    CI_REGISTRY_IMAGE: bbpgitlab.epfl.ch:5050/viz/brayns/braynscircuitstudiobackend/bcss

.bcss-publish:
  extends:
    - .publish-image-using-kaniko
    - .kube
    - .bcss-common

# This is used for testing only during Merge Request
bcss-build:
  extends:
    - .build-image-using-kaniko
    - .kube
    - .bcss-common
  stage: test
  rules:
    - if: $CI_MERGE_REQUEST_IID

# All new commits in the "develop" branch are built into a "latest" tag
bcss-publish-latest:
  extends: .bcss-publish
  stage: publish
  variables:
    REGISTRY_IMAGE_TAG: latest
  rules:
    - if: $CI_COMMIT_BRANCH == "develop"

# Once a commit tag with version is pushed to "master", it builds a new version image
bcss-publish-version:
  extends: .bcss-publish
  variables:
    REGISTRY_IMAGE_TAG: $CI_COMMIT_TAG
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
    - if: $CI_COMMIT_TAG =~ /^[0-9]+\.[0-9]+(\.[0-9]+)?$/
