include:
  - project: viz/ci/gitlabpipelines
    file: index.yml

.publish-bcsb:
  extends: .publish-image-using-kaniko
  tags:
    - kubernetes
  variables:
    CI_REGISTRY_IMAGE: bbpgitlab.epfl.ch:5050/viz/brayns/braynscircuitstudiobackend
    KUBERNETES_MEMORY_LIMIT: 2Gi
    KUBERNETES_MEMORY_REQUEST: 2Gi

build:
  extends: .build-image-using-kaniko
  tags:
    - kubernetes
  variables:
    KUBERNETES_MEMORY_LIMIT: 2Gi
    KUBERNETES_MEMORY_REQUEST: 2Gi

publish-latest:
  extends: .publish-bcsb
  variables:
    REGISTRY_IMAGE_TAG: latest
  rules:
    - if: $CI_COMMIT_BRANCH == "develop"

publish-version:
  extends: .publish-bcsb
  variables:
    REGISTRY_IMAGE_TAG: $CI_COMMIT_TAG
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
    - if: $CI_COMMIT_TAG =~ /^[0-9]+\.[0-9]+(\.[0-9]+)?$/
