version: '3.7'
services:
  bcsb:
    build:
      context: .
      dockerfile: bcsb.dockerfile
    env_file:
      - .env
    depends_on:
      - database
      - redis
    ports:
      - "8000:8000"
#      - "${DJANGO_BACKEND_PORT:-8000}:${DJANGO_BACKEND_PORT:-8000}"
#      - "587:587"
#      - "25:25"
    volumes:
      - ${COMPOSE_APP_PATH:-.}:/usr/src/
    command: sh -c "/usr/src/bcsb-entrypoint.sh"

  database:
    image: postgres:13
    env_file:
      - .env
    ports:
      - "${COMPOSE_POSTGRES_PORT:-5432}:5432"

  redis:
    image: redis:latest
    env_file:
      - .env
    ports:
      - "${COMPOSE_REDIS_PORT:-6379}:6379"

  bcss:
    build:
      context: .
      dockerfile: bcss.dockerfile
    env_file:
      - .env
    ports:
      - "${BCSS_PORT:-8666}:${BCSS_PORT:-8666}"
    volumes:
      - ${BCSS_APP_PATH:-.}:/usr/src/
      - /Users/Shared/gpfs/bbp.cscs.ch/project/proj3/TestData/install/share/BBPTestData/circuitBuilding_1000neurons/:/gpfs/bbp.cscs.ch/project/proj3/TestData/install/share/BBPTestData/circuitBuilding_1000neurons/
    command: sh -c "/usr/src/bcss-entrypoint.sh"
