version: '3.7'
services:
  app:
    build:
      context: .
    env_file:
      - .env
    ports:
      - "${APP_PORT:-8000}:${APP_PORT:-8000}"
    volumes:
      - ${APP_PATH:-.}:/usr/src/
      - ${GPFS_PATH:-/gpfs/}:/gpfs/
    command: sh -c "/usr/src/entrypoint.sh"
