# Generated by Django 4.1b1 on 2022-07-21 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bcsb_sessions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Allocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("unicore_job_id", models.UUIDField(unique=True)),
                ("project", models.CharField(max_length=30)),
                ("hostname", models.CharField(blank=True, max_length=50)),
                ("status", models.CharField(max_length=20)),
                ("script", models.TextField(blank=True)),
                ("stdout", models.TextField(blank=True)),
                ("stderr", models.TextField(blank=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bcsb_sessions.session"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
