# Generated by Django 3.2.9 on 2022-07-13 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('allocations', '0001_initial'),
        ('unicore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='unicore_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unicore.unicorejob'),
        ),
    ]
