# Generated by Django 4.1b1 on 2022-07-21 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("allocations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="allocation",
            name="bcss_ws_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="allocation",
            name="brayns_ws_url",
            field=models.URLField(blank=True),
        ),
    ]
