# Generated by Django 4.1b1 on 2022-07-20 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("allocations", "0002_remove_allocation_port"),
    ]

    operations = [
        migrations.AddField(
            model_name="allocation",
            name="stderr",
            field=models.TextField(blank=True),
        ),
    ]
